# Generated by Django 3.2.16 on 2022-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-08-21'),
            preserve_default=False,
        ),
    ]
